messages:
  forOnlyPlayers: "&cThis command is for players only."
  balance: "&bYou have {balance} points."
  balanceOthers: "&b{player} has {balance} EM points."
  noPerm: "&cYou don't have permission to do this."
  notEnoughBalance: "&c{player} doesn't have enought points."
  successfullySet: "You have successfully set {player}'s points to {balance}."
  successfullyReset: "You have successfully reset {player}'s points."
  successfullyGiven: "You have successfully given {balance} points to {player}."
  successfullyTaken: "You have successfully taken {balance} points to {player}."
  successfullyReloaded: "Plugin successfully relaoded and datas saved to data.yml."
  automaticBackup: "Plugin automatically backed up."
usages:
  give: "Usage of this command is /em give <player> <amount>."
  take: "Usage of this command is /em take <player> <amount>"
  set: "Usage of this command is /em set <player> <amount>"
  reset: "Usage of this command is /em reset <player>"
settings:
  #In minutes
  autoRestartPeriod: 30
