main: me.em.EMPoint
name: EMPoint
author: MetuMortis
api-version: 1.18
version: 1.0
softdepend: ["PlaceholderAPI"]
commands:
  prestij:
    description: "Plugin's main Command"
    usage: "/presitj <operation>"

