main: me.em.EMPoint
name: EMPoint
author: MetuMortis
api-version: 1.16
version: 1.0
softdepend: ["PlaceholderAPI"]
commands:
  em:
    description: "Plugin's main Command"
    usage: "/em <operation>"

